const mongoose = require('mongoose')
require('../db')
const BeachModel = require('../models/Beach.model')


const beaches = [
    { spotId: '584204204e65fad6a7709472', spotName: 'PANTIN 🇺🇸 ', spotDescription:'in Galicia is an exposed beach break that is often working and works all around the year. Offshore winds blow from the southeast with some shelter here from northeast winds. Most of the surf here comes from groundswells and the ideal swell direction is from the northwest. The beach break offers both left and right hand waves. Best around low tide. Often Crowded. Overcrowding can even make surfing hazardous.', },
    { spotId: '5842041f4e65fad6a7708c88', spotName: 'MUNDAKA', spotDescription:'The combination of river and oceanic currents have sculpted a sandbank of almost mathematical perfection to produce one of the most awesome waves on the planet. Access is simple enough, a gentle paddle from the harbor, but this isnt an easy wave to surf. The water detonates onto the shallow sand bank in a steep and pitching lunge, and although it is sand-bottomed, from here on in it breaks like a reef. Those who hit the bottom do so hard. The outer peak is dominated by a pack, but even the scraps way down the line can offer great barrels. Mundakas fantastically shaped rivermouth sandbar creates solid, 200-yard-long, top-to-bottom barrels.', },
    { spotId: '5842041f4e65fad6a7708d0f', spotName: 'J- BAY', spotDescription:'in Jeffreys Bay Coast is an exposed beach and reef break that has dependable surf, although summer tends to be mostly flat. Offshore winds blow from the west northwest. Clean groundswells prevail and the ideal swell angle is from the south.. Sometimes crowded. Watch out for sharks ,rocks,mussel shells.', },
    { spotId: '5842041f4e65fad6a7708b43', spotName: 'PUERTO ESCONDIDO', spotDescription:'in Oaxaca is an exposed beach and point break that has very reliable surf. Summer offers the favoured conditions for surfing. Offshore winds blow from the north northeast. Tends to receive distant groundswells and the best swell direction is from the south southwest. Waves at the beach break both left and right Sometimes crowded. Watch out for rips and sharks.', },
    { spotId: '5842041f4e65fad6a7708bc3', spotName: 'SUPERTUBOS', spotDescription:'Supertubos is one of the best waves in Europe. Theres one main peak with a super-fast (though makeable) left, and a somewhat shorter right, and one other peak down the beach thats not quite as perfect but still way better than your average day at most beachbreaks.', },
    { spotId: '5842041f4e65fad6a7708dbf', spotName: 'TEAHUPO’O', spotDescription:'in Tahiti is an exposed reef break that has very reliable surf. Winter is the optimum time of year for surfing here. The best wind direction is from the north northeast. Tends to receive distant groundswells and the best swell direction is from the south. A left hand reef break. Good surf at all stages of the tide. Often Crowded. Take care of rocks,urchins and sharks.', },
    { spotId: '5842041f4e65fad6a7708dc5', spotName: 'CLOUDBREAK', spotDescription:'in Mamanucas is a sheltered reef/bombora break that has consistent surf, although summer tends to be mostly flat. The best wind direction is from the southwest. Groundswells more frequent than windswells and the ideal swell direction is from the southwest. A left hand reef break. Rarely crowded here. Beware of urchins, cost, rips and rocks.', },
    { spotId: '5842041f4e65fad6a7708c28', spotName: 'MARGARET RIVER', spotDescription:'in Margaret River is a sheltered river break that has very consistent waves and works all around the year. Offshore winds blow from the east. Waves can be ok even in light onshore winds Groundswells more frequent than windswells and the ideal swell angle is from the south southwest. The river breaks favour rights. When the surf is up, it can get quite busy in the water. Watch out for rips and rocks.', },
    { spotId: '5842041f4e65fad6a7708be5', spotName: 'SNAPPER ROCKS', spotDescription:'on the Gold Coast is a fairly exposed point break that has very consistent surf. Autumn and winter are the best times of year for waves. Works best in offshore winds from the southeast. Waves just as likely from local windswells as from distant groundswells and the ideal swell direction is from the east. Good surf at all stages of the tide. Take care of rips, rocks and locals.', },
    { spotId: '5842041f4e65fad6a7708d30', spotName: 'G- LAND', spotDescription:'in East Java is an exposed reef break that has very consistent waves. May-Oct (Dry Season) is the optimum time of year for waves. Offshore winds are from the east with some shelter here from southeast winds. Most of the surf here comes from groundswells and the best swell direction is from the southwest. A left hand reef break. Best around mid tide. When its working here, it can get crowded. Beware of urchins, rocks and rips.', },
    { spotId: '584204214e65fad6a7709c91', spotName: 'PIPELINE', spotDescription:'Backdoor was somewhat ignored during Pipelines first golden days in the 1970s. It makes you wonder how many heaving barrels roared right off the peak before everyone kind of clicked on it. The wave relies on a slight breaking up of swell lines from the northwest (shorter to mid period swells are best, of a swell combo) and a thin channel between the Pipe reef and Off-The-Wall.', },
    { spotId: '5842041f4e65fad6a7708c8e', spotName: 'LA GRAVIERE', spotDescription:'in Landes is a sandbar break that has pretty consitent surf. The optimum time of year for waves is autumn. Works best in offshore winds from the east. Tends to receive a mix of groundswells and windswells and the best swell direction is from the west. The sandbar breaks offer lefts and rights. When the surf is up, it can get quite busy in the water. The crowds in the water make a gath helmet a good idea.', },
    { spotId: '584204204e65fad6a7709490', spotName: 'EL PALMAR', spotDescription:'in Andalucia is a fairly exposed beach break that has reasonably consistent surf. Winter and spring are the best times of year to visit. Works best in offshore winds from the east. Poor surf in light onshore winds Tends to receive a mix of groundswells and windswells and the ideal swell direction is from the southwest. The beach break offers mainly right hand waves. Good surf at all stages of the tide. Often Crowded. Watch out for dangerous rips.', },
    { spotId: '5842041f4e65fad6a7708bc4', spotName: 'COXOS', spotDescription:'in Ericeira is an exposed reef break that has fairly consistent surf and can work at any time of the year. Offshore winds blow from the southeast. Windswells and groundswells in equal measure and the best swell direction is from the north northwest. Often Crowded. Watch out for rips and crowds.', },
  ]

  BeachModel.insertMany(beaches).then((allBeachesDB) => {
    console.log('All beaches seeded!', allBeachesDB)
    return mongoose.connection.close()
})
.then(() => {
    console.log('DB closed')
})

.catch((err) => {
    console.log('There was a problem seeding', err)
})